title: John Ward
description: Personal site of John Ward, Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsjohnward.com" # the base hostname & protocol for your site

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
