title: John Ward
description: >
    Personal site of John Ward, Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsjohnward.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
